name: CI

on:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**' # don't run (again) when on these special branches created during merge groups; the `on: merge_group` already triggers it.
  merge_group:
  pull_request:

env:
  PYTHONUNBUFFERED: True
  PRE_COMMIT_HOME: ${{ github.workspace }}/.precommit_cache

permissions:
  id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
  contents: read # need to explicitly provide this whenever defining permissions because the default value is 'none' for anything not explicitly set when permissions are defined

jobs:
  get-values:
    uses: ./.github/workflows/get-values.yaml
    permissions:
      contents: write # needed for updating dependabot branches

  check-skip-duplicate:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    permissions:
      contents: read
      pull-requests: read # needed to check if PR exists for current branch
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - id: check
        uses: ./.github/actions/check-skip-duplicates

  pre-commit:
    needs:
      - get-values
      - check-skip-duplicate
    if: needs.check-skip-duplicate.outputs.should-run == 'true'
    uses: ./.github/workflows/pre-commit.yaml
    permissions:
      id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
      contents: write # needed for mutex
    with:
      python-version: 3.12.11

  ephemeral-test:
    uses: ./.github/workflows/pulumi-aws.yml
    needs:
      - pre-commit
      - get-values
      - check-skip-duplicate
    if: needs.check-skip-duplicate.outputs.should-run == 'true' && (github.event_name == 'pull_request' || github.event_name == 'merge_group')
    permissions:
      id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
      contents: write # needed for mutex
      pull-requests: write # needed to potentially post the preview on the PR as a comment
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: test-${{ needs.get-values.outputs.pr-short-num }}
      PYTHON_VERSION: 3.12.11
      PROJECT_DIR: .
      DEPLOY_SCRIPT_MODULE_NAME: cloud_courier_infrastructure.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: InfraPreview--cloud-courier-infrastructure
      PULUMI_UP_ROLE_NAME: InfraDeploy--cloud-courier-infrastructure
      PULUMI_UP: true
      PULUMI_DESTROY: true
      AWS_ACCOUNT_ID: "423623840054"

  pulumi-staging:
    uses: ./.github/workflows/pulumi-aws.yml
    needs:
      - pre-commit
      - check-skip-duplicate
    if: needs.check-skip-duplicate.outputs.should-run == 'true'
    permissions:
      id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
      contents: write # needed for mutex
      pull-requests: write # needed to potentially post the preview on the PR as a comment
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: staging
      PYTHON_VERSION: 3.12.11
      PROJECT_DIR: .
      DEPLOY_SCRIPT_MODULE_NAME: cloud_courier_infrastructure.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: InfraPreview--cloud-courier-infrastructure
      PULUMI_UP: ${{ github.ref == 'refs/heads/main' }}
      PULUMI_UP_ROLE_NAME: InfraDeploy--cloud-courier-infrastructure
      AWS_ACCOUNT_ID: "354918380870"
      SHOW_PREVIEW_COMMENT_ON_PR: ${{ github.event_name == 'pull_request' }}

  pulumi-prod:
    uses: ./.github/workflows/pulumi-aws.yml
    needs:
      - pulumi-staging
      - check-skip-duplicate
    if: needs.check-skip-duplicate.outputs.should-run == 'true' && (github.event_name == 'pull_request' || github.event_name == 'merge_group' || github.ref == 'refs/heads/main')
    permissions:
      id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
      contents: write # needed for mutex
      pull-requests: write # needed to potentially post the preview on the PR as a comment
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: prod
      PYTHON_VERSION: 3.12.11
      PROJECT_DIR: .
      DEPLOY_SCRIPT_MODULE_NAME: cloud_courier_infrastructure.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: InfraPreview--cloud-courier-infrastructure
      PULUMI_UP: ${{ github.ref == 'refs/heads/main' }}
      PULUMI_UP_ROLE_NAME: InfraDeploy--cloud-courier-infrastructure
      AWS_ACCOUNT_ID: "872515290027"
      SHOW_PREVIEW_COMMENT_ON_PR: ${{ github.event_name == 'pull_request' }}

  confirm-on-tagged-copier-template:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: ./.github/workflows/confirm-on-tagged-copier-template.yaml

  workflow-summary:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    needs:
      - get-values
      - pre-commit
      - check-skip-duplicate
      - confirm-on-tagged-copier-template
      - ephemeral-test
      - pulumi-staging
      - pulumi-prod
    permissions:
      statuses: write # needed for updating status on Dependabot PRs
    if: always()
    steps:
      - name: fail if prior job failure
        run: |
          success_pattern="^(skipped|success)$" # these are the possibilities: https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#needs-context

          if [[ ! "${{ needs.check-skip-duplicate.result }}" =~ $success_pattern ]] ||
            [[ ! "${{ needs.pre-commit.result }}" =~ $success_pattern ]] ||
            [[ ! "${{ needs.confirm-on-tagged-copier-template.result }}" =~ $success_pattern ]]; then
            [[ ! "${{ needs.ephemeral-test.result }}" =~ $success_pattern ]] ||
            [[ ! "${{ needs.pulumi-staging.result }}" =~ $success_pattern ]] ||
            [[ ! "${{ needs.pulumi-prod.result }}" =~ $success_pattern ]]; then
            echo "❌ One or more jobs did not finish with skipped or success"
            exit 1
          fi
          echo "✅ All jobs finished with skipped or success"

      - name: Mark the required-check as succeeded so the PR can be merged
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.pull_request.statuses_url }}" \
            -f state=success -f context="required-check" -f description="✅ All required checks passed in the job triggered by pull_request" \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Mark updated dependabot hash commit as succeeded
        if: needs.get-values.outputs.dependabot-commit-created == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            "/repos/${{ github.repository }}/statuses/${{ needs.get-values.outputs.new-dependabot-sha }}" \
            -f state=success -f context="required-check" -f description="Initial CI run passed" \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
