name: CI

on:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**' # don't run (again) when on these special branches created during merge groups; the `on: merge_group` already triggers it.
  merge_group:
  pull_request:

env:
  PYTHONUNBUFFERED: True
  PRE_COMMIT_HOME: ${{ github.workspace }}/.precommit_cache

permissions:
    id-token: write
    contents: write # needed for mutex, and updating dependabot branches
    statuses: write # needed for updating status on Dependabot PRs

jobs:
  get-values:
    uses: ./.github/workflows/get-values.yaml

  pre-commit:
    needs: [ get-values ]
    uses: ./.github/workflows/pre-commit.yaml
    with:
      python-version: 3.12.11

  ephemeral-test:
    uses: ./.github/workflows/pulumi-aws.yml
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    needs: [ pre-commit, get-values ]
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: test-${{ needs.get-values.outputs.pr-short-num }}
      PYTHON_VERSION: 3.12.11
      DEPLOY_SCRIPT_MODULE_NAME: cloud_courier_infrastructure.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: InfraPreview--cloud-courier-infrastructure
      PULUMI_UP_ROLE_NAME: InfraDeploy--cloud-courier-infrastructure
      PULUMI_UP: true
      PULUMI_DESTROY: true
      AWS_ACCOUNT_ID: "423623840054"

  pulumi-staging:
    uses: ./.github/workflows/pulumi-aws.yml
    needs: [ pre-commit ]
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: staging
      PYTHON_VERSION: 3.12.11
      DEPLOY_SCRIPT_MODULE_NAME: cloud_courier_infrastructure.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: InfraPreview--cloud-courier-infrastructure
      PULUMI_UP: ${{ github.ref == 'refs/heads/main' }}
      PULUMI_UP_ROLE_NAME: InfraDeploy--cloud-courier-infrastructure
      AWS_ACCOUNT_ID: "354918380870"

  pulumi-prod:
    uses: ./.github/workflows/pulumi-aws.yml
    if: github.ref == 'refs/heads/main'
    needs: [ pulumi-staging ]
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: prod
      PYTHON_VERSION: 3.12.11
      DEPLOY_SCRIPT_MODULE_NAME: cloud_courier_infrastructure.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: InfraPreview--cloud-courier-infrastructure
      PULUMI_UP: true
      PULUMI_UP_ROLE_NAME: InfraDeploy--cloud-courier-infrastructure
      AWS_ACCOUNT_ID: "872515290027"


  required-check:
    runs-on: ubuntu-24.04
    needs: [ get-values, ephemeral-test, pulumi-staging, pulumi-prod ]
    if: always()
    steps:
      - name: Show job status
        run: |
          echo ${{ needs.pulumi-staging.result }}
          echo ${{ needs.get-values.result }}
          echo ${{ needs.ephemeral-test.result }}
          echo ${{ needs.pulumi-prod.result }}
      - name: fail if prior job failure
        if: needs.pulumi-staging.result != 'success' || (needs.get-values.result != 'success' && needs.get-values.result != 'skipped') || (needs.ephemeral-test.result != 'success' && needs.ephemeral-test.result != 'skipped') || (needs.pulumi-prod.result != 'success' && needs.pulumi-prod.result != 'skipped')
        run: |
          exit 1
      - name: Mark updated Dependabot commit of devcontainer hash as succeeded
        if: needs.get-values.outputs.dependabot-commit-created == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            "/repos/${{ github.repository }}/statuses/${{ needs.get-values.outputs.new-dependabot-sha }}" \
            -f state=success -f context="required-check" -f description="Initial CI run passed" \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
